version: '3.8'

services:
  crawler:
    build: .
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    command: python wizard_cli.py crawl

  doc_search:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GOOGLE_AI_KEY=${GOOGLE_AI_KEY}
    command: uvicorn search_api:app --host 0.0.0.0 --port 8000 --reload
    profiles:
      - api 

  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./knowledge_base:/app/knowledge_base
    environment:
      - PORT=5000
    restart: unless-stopped 